var data = [
    {
      "question": "What is camelCase?",
      "answers": [
        {
          "text": "A way of capitalizing letters to make reading JS easier",
          "isCorrect": true
        },
        {
          "text": "a font family.",
          "isCorrect": false
        },
        {
          "text": "a camel in a suitcase",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "What does the array.push() method do?",
      "answers": [
        {
          "text": "Clears the last element of an array",
          "isCorrect": false
        },
        {
          "text": "adds one or more elements to end of array",
          "isCorrect": true
        },
        {
          "text": "shrinks an array",
          "isCorrect": false
        }
      ]
    },
    {
      "question": " What are items in an array separated by?",
      "answers": [
        {
          "text": "comma",
          "isCorrect": true
        },
        {
          "text": "slashes",
          "isCorrect": false
        },
        {
          "text": "dashes",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "console.log() is a ...",
      "answers": [
        {
          "text": "method",
          "isCorrect": true
        },
        {
          "text": " variable",
          "isCorrect": false
        },
        {
          "text": "crime against your family",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "by default a div is a _____ element",
      "answers": [
        {
          "text": "inline",
          "isCorrect": false
        },
        {
          "text": "block",
          "isCorrect": true
        },
        {
          "text": "period table of",
          "isCorrect": false
        }
      ]
    }
  ];